title: Kien Vu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm analyst and blogger
  <br><br>
  I use data to solve problem
  <br><br>
  <a href="https://twitter.com/KienVu2368">twitter</a> | <a href="zero2368@gmail.com">email</a> | <a href="https://medium.com/@kien.vu">blog</a> | <a href="https://github.com/KienVu2368">github</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-174653341-1 # your Google Analytics tracking ID here

